### PR TITLE
InvRichardsonMultiPrec: add support for CG as the inner solver

### PR DESCRIPTION
**Pull request by kostrzewa**
Let's try https://github.com/JeffersonLab/qphix/pull/86 again. I've enabled the Richardson test in the Wilson dslash test.

### CODE REVIEW

**Comment by kostrzewa** [comment]
I noticed some odd behaviour in the Dslash test which I can't quite pin down, perhaps you know more. For the random gauge tested here, BiCGstab takes more iterations than CG for what I guess is the same problem since neither the source nor the gauge field change between the runs of different solvers. Now, since this is a **weak field** random gauge, could it be that the smallest eigenvalue of the operator is larger than one with the given parameters? (which would make the normal operator better conditioned, thus explaining the number of iterations) I just want to make sure that we didn't inadvertenly introduce something silly. In my tests on real gauges I consistently get BiCGstab outperforming CG as expected.

**Comment by kostrzewa** [comment]
I think this is safe to pull in.

**Comment by kostrzewa** [comment]
ping

**Comment by martin-ueding** [comment]
Since the tests seem to work, I don't see why this would break something. So perhaps I can merge that into `devel`?

**Comment by kostrzewa** [comment]
Do the tests now include the Richardson solver?

**Comment by martin-ueding** [comment]
The Richardson solver is used in [Wilson](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4845), [Clover](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4080) and [TM Clover](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4080). It is missing in TM Wilson.

So I will try to get that test enabled. But having three operators tested should be sufficient for this merge, right?

**Comment by kostrzewa** [comment]
Yes, I think we're fine then, I don't think that we broke anything on the interface side either.

**Comment by martin-ueding** [comment]
The Richardson solver is used in [Wilson](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4845), [Clover](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4080) and [TM Clover](https://travis-ci.org/JeffersonLab/qphix/jobs/288917633#L4080). It is missing in TM Wilson.

So I will try to get that test enabled. But having three operators tested should be sufficient for this merge, right?

**Comment by martin-ueding** [comment]
The BiCGStab test is now enabled for TM Wilson and works on my machine. It will now build on Travis CI, then we can merge that into `devel` and have that test running as well.

**Pull request merged**
